# Generated by Django 3.2.18 on 2023-07-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0017_repeat_every'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='GSTIN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
