# Generated by Django 3.2.18 on 2023-07-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0018_customer_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='hsn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='invacc',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='additem',
            name='tax',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
