# Generated by Django 4.2.1 on 2023-07-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0021_purchase_order_purchase_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_items',
            name='tax',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
