# Generated by Django 4.2.1 on 2023-07-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0022_alter_purchase_order_items_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='Org_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='Org_street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='customer_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='customer_street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
