# Generated by Django 4.2.1 on 2023-07-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0025_purchase_order_org_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring_bills',
            name='cgst',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recurring_bills',
            name='igst',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recurring_bills',
            name='sgst',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
