# Generated by Django 4.2.1 on 2023-07-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0026_alter_recurring_bills_cgst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order_items',
            name='tax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
